<script setup lang="ts">
definePageMeta({layout:'admin'}); useSeoMeta({title:'项目管理'})
type Project={id:number;name:string;summary:string;status:'ACTIVE'|'ARCHIVED'|'SOLD'|'BUILDING';websiteUrl:string|null;githubUrl:string|null;techStack:string[];sort:number}
const session=useState<{csrfToken:string}|null>('admin-session'); const {data:response,refresh}=await useFetch<{data:Project[]}>('/api/admin/projects'); const projects=computed(()=>response.value?.data||[])
const blank=()=>({name:'',summary:'',status:'ACTIVE' as Project['status'],websiteUrl:'',githubUrl:'',techStack:'',sort:0}); const form=reactive(blank()); const editingId=ref<number|null>(null); const errorMessage=ref(''); const pending=ref(false)
function edit(p:Project){editingId.value=p.id;Object.assign(form,{...p,websiteUrl:p.websiteUrl||'',githubUrl:p.githubUrl||'',techStack:p.techStack.join(', ')})} function reset(){editingId.value=null;Object.assign(form,blank());errorMessage.value=''}
async function save(){if(!session.value)return;pending.value=true;errorMessage.value='';try{const body={...form,techStack:form.techStack.split(/[,，]/).map(x=>x.trim()).filter(Boolean),sort:Number(form.sort)};await $fetch(editingId.value?`/api/admin/projects/${editingId.value}`:'/api/admin/projects',{method:editingId.value?'PUT':'POST',body,headers:{'X-CSRF-Token':session.value.csrfToken}});reset();await refresh()}catch(e:any){errorMessage.value=e?.data?.error?.message||'保存失败'}finally{pending.value=false}}
async function remove(p:Project){if(!session.value||!confirm(`确定永久删除“${p.name}”吗？`))return;await $fetch(`/api/admin/projects/${p.id}`,{method:'DELETE',headers:{'X-CSRF-Token':session.value.csrfToken}});await refresh()}
</script>
<template><section class="manage"><header><p class="eyebrow">CONTENT</p><h1>项目管理</h1></header><div class="layout"><UCard><template #header><strong>{{editingId?'编辑项目':'新建项目'}}</strong></template><form class="form" @submit.prevent="save"><UFormField label="名称" required><UInput v-model="form.name" class="w-full"/></UFormField><UFormField label="摘要" required><UTextarea v-model="form.summary" class="w-full"/></UFormField><UFormField label="状态"><select v-model="form.status"><option value="ACTIVE">已上线</option><option value="BUILDING">开发中</option><option value="SOLD">已出售</option><option value="ARCHIVED">已归档</option></select></UFormField><UFormField label="网站 URL"><UInput v-model="form.websiteUrl" class="w-full"/></UFormField><UFormField label="GitHub URL"><UInput v-model="form.githubUrl" class="w-full"/></UFormField><UFormField label="技术栈（逗号分隔）"><UInput v-model="form.techStack" class="w-full"/></UFormField><UFormField label="排序"><UInput v-model.number="form.sort" type="number" class="w-full"/></UFormField><UAlert v-if="errorMessage" color="error" :description="errorMessage"/><div><UButton type="submit" :loading="pending">保存</UButton><UButton v-if="editingId" color="neutral" variant="ghost" @click="reset">取消</UButton></div></form></UCard><div class="cards"><UCard v-for="p in projects" :key="p.id"><strong>{{p.name}}</strong><p>{{p.summary}}</p><small>{{p.techStack.join(' · ')}} · 排序 {{p.sort}}</small><template #footer><UButton size="sm" variant="ghost" color="neutral" @click="edit(p)">编辑</UButton><UButton size="sm" variant="ghost" color="error" @click="remove(p)">删除</UButton></template></UCard><p v-if="!projects.length">暂无项目</p></div></div></section></template>
<style scoped>.manage{display:grid;gap:24px}.manage h1{margin:0}.layout{display:grid;grid-template-columns:360px 1fr;gap:24px;align-items:start}.form,.cards{display:grid;gap:16px}.form select{width:100%;padding:8px;border:1px solid var(--color-border);border-radius:6px;background:var(--color-background);color:inherit}.cards p{color:var(--color-text-secondary);line-height:1.6}.cards small{color:var(--color-text-secondary)}@media(max-width:850px){.layout{grid-template-columns:1fr}}</style>
